# Generated by Django 3.0.3 on 2020-03-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchID', models.IntegerField(primary_key=True, serialize=False)),
                ('branchCity', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default=None, max_length=50)),
                ('lastName', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(default=None, max_length=50)),
                ('street2', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=2)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('customerID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('accountType', models.CharField(default=None, max_length=50)),
                ('balance', models.FloatField()),
                ('customerID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
            ],
        ),
    ]
