# Generated by Django 3.0.3 on 2020-03-09 23:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default=None, max_length=150)),
                ('author', models.CharField(max_length=150, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='address',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='addressID',
            field=models.IntegerField(default=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Comment'),
        ),
    ]
