# Generated by Django 3.0.3 on 2020-03-08 23:00

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200307_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default=None, max_length=150)),
                ('author', models.CharField(max_length=150, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank.Comment'),
        ),
    ]
