# Generated by Django 3.0.3 on 2020-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200309_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Comment'),
        ),
    ]
