# Generated by Django 3.0.3 on 2020-03-08 23:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200308_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=250, verbose_name=django.contrib.auth.models.User),
        ),
    ]
